import {StyleSheet} from 'react-native';

export const viewPostStyles = StyleSheet.create({
  noImageContainer: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    backgroundColor: '#f0f0f0',
    height: 200,
  },
  noImageText: {
    color: '#888',
    fontSize: 16,
  },
  instructionsContainer: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#2441D024',
    borderRadius: 8,
    marginTop: 12,
    marginBottom: 12,
  },
  instructionsContainer2: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#2441D024',
    borderRadius: 8,
    marginTop: 12,
    marginBottom: 12,
    width: '90%',
    alignSelf: 'center',
  },
  instructionsHeadingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  instructionsHeading: {
    fontSize: 14,
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    marginBottom: 4,
    color: 'black',
  },
  headingIcon: {
    width: 13.49,
    height: 13.49,
  },
  line: {
    height: 1,
    width: '100%',
    backgroundColor: '#2441D024',
  },
  instructionsContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
    paddingRight: 15,
    alignItems: 'center',
    marginTop: 8,
  },
  instructionItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  instructionTextRed: {
    color: '#E64646',
    fontWeight: '600',
    fontFamily: 'Helvetica',
    fontSize: 10.32,
  },
  instructionTextGreen: {
    color: '#188038',
    fontFamily: 'Helvetica',
    fontWeight: '600',
    fontSize: 10.32,
  },
  postContainer: {
    padding: 10,
    margin: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
  },

  imagetext: {
    fontSize: 10,
    color: 'black',
    marginTop: 10,
    textAlign: 'center',
  },
  apartmenttype: {
    color: 'gray',
    fontSize: 12,
    marginTop: 5,
  },
  address: {
    color: 'gray',
    fontSize: 12,
  },
  facilityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 2,
    marginBottom: 10,
  },
  facilityIcon: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  container: {
    borderWidth: 1,
    borderColor: '#2441D024',
    borderRadius: 8,
    marginVertical: 8,
    overflow: 'hidden',
  },
  imageContainer: {
    padding: 8,
  },
  image: {
    width: '100%',
    height: 204,
    borderRadius: 8,
  },
  detailsContainer: {
    padding: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
    width: '65%',
    height: 'auto',
    flexWrap: 'wrap',
  },
  looking_title: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
    width: '80%',
    height: 'auto',
    flexWrap: 'wrap',
  },
  price: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2441D0',
  },
  price2: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 12,
    fontWeight: '600',
    color: '#2441D0',
  },
  smallText: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 12,
    fontWeight: '400',
    color: 'gray',
    marginTop: 5,
  },
  smallText2: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 12,
    fontWeight: '400',
    color: 'gray',
    lineHeight: 17.64,
  },
  smallText3: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 12,
    fontWeight: '600',
    color: 'black',
    marginTop: 7,
    lineHeight: 17.64,
  },
  facilitiesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    marginLeft: 10,
  },
  facilities: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
  },
  icon: {
    width: 16,
    height: 16,
    marginRight: 4,
  },
  availability: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 14,
    lineHeight: 16.8,
    fontWeight: '400',
    color: 'gray',
    alignSelf: 'flex-end',
  },
  availabilityContainer: {
    marginBottom: 10,
    justifyContent: 'flex-end',
  },
  date: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 14,
    fontWeight: '700',
    color: '#2441D0',
    textAlign: 'right',
  },
  date2: {
    fontFamily: 'Helvetica Now Display',
    fontSize: 12,
    lineHeight: 17.64,
    fontWeight: '500',
    color: '#2441D0',
    textAlign: 'right',
  },
  labelContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#2441D0',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 18,
  },
  labelContainer2: {
    position: 'absolute',
    top: 35,
    right: 10,
    backgroundColor: '#2441D0',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 18,
  },
  label: {
    color: 'white',
    fontFamily: 'Helvetica Now Display',
    fontSize: 10,
    fontWeight: '400',
  },
  offeringLabelContainer: {
    position: 'absolute',
    top: 8,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Transparent black background
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 18,
    marginTop: 4,
    marginRight: 4,
  },
  offeringLabelContainer2: {
    position: 'absolute',
    top: 40,
    right: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Transparent black background
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 18,
    marginTop: 4,
    marginRight: 4,
  },
  offeringLabel: {
    color: 'white',
    fontFamily: 'Helvetica Now Display',
    fontSize: 10,
    fontWeight: '400',
  },
});
